import { SidebarProvider } from "@/components/context/SidebarContext";
import { peyda } from "../utils/fonts";
import "./globals.css";

export const metadata = {
  title: "Fitno",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={peyda.className}>{children}</body>
    </html>
  );
}
