import { peyda } from "../utils/fonts";
import "./globals.css";
import TanstackQueryProvider from "@/provider/TanstackQueryProvider";

export const metadata = {
  title: "Fitno",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={peyda.className}>
         <TanstackQueryProvider>
        {children}
        </TanstackQueryProvider>
        </body>
    </html>
  );
}
